//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancient_Ancestry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ancient_Ancestry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CA NAME=&apos;ADAM AND EVE&apos;&gt;
        ///	&lt;CA NAME=&apos;LBK-LOS-CA1-BR2-UI&apos;&gt;
        ///		&lt;KITS&gt;
        ///			&lt;KIT ID=&apos;999916&apos; NAME=&apos;Linearbandkeramik&apos;/&gt;
        ///			&lt;KIT ID=&apos;999918&apos; NAME=&apos;Loschbour&apos;/&gt;
        ///			&lt;KIT ID=&apos;999919&apos; NAME=&apos;Clovis Anzick-1&apos;/&gt;
        ///			&lt;KIT ID=&apos;999933&apos; NAME=&apos;BR2&apos;/&gt;
        ///			&lt;KIT ID=&apos;999935&apos; NAME=&apos;Ust-Ishim&apos;/&gt;
        ///		&lt;/KITS&gt;
        ///		&lt;SEGMENTS&gt;
        ///			&lt;SEGMENT CHR=&apos;8&apos; START=&apos;43383815&apos;  END=&apos;43791691&apos;/&gt;
        ///		&lt;/SEGMENTS&gt;
        ///		&lt;CA NAME=&apos;LBK-LOS-CA1-BR2&apos;&gt;
        ///			&lt;KITS&gt;
        ///				&lt;KIT ID=&apos;999916&apos; NAME=&apos;Linearbandkeramik&apos;/&gt;
        ///				&lt;KIT ID=&apos;999918&apos; NAME=&apos;Loschbour&apos;/&gt;
        ///				&lt;KI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string atree {
            get {
                return ResourceManager.GetString("atree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ibd {
            get {
                object obj = ResourceManager.GetObject("ibd", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
